# Generated by Django 2.0.4 on 2018-04-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='tipo',
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_entrada',
            field=models.CharField(choices=[('EN', 'Entrada'), ('SA', 'Saída')], default='EN', max_length=2),
        ),
    ]
