# Generated by Django 2.0.4 on 2018-05-01 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20180413_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
